els-ASAP auto commit file/tag infiniband-diags-1.6.4-1.el6.src.rpm

diff --git a/src/scripts/ibcheckerrs b/src/scripts/ibcheckerrs
--- a/src/scripts/ibcheckerrs
+++ b/src/scripts/ibcheckerrs
@@ -1,15 +1,15 @@
-#!/bin/bash
+#!/bin/sh
 
 IBPATH=${IBPATH:-/usr/local/sbin}
 
-function usage() {
+usage() {
 	echo Usage: `basename $0` "[-h] [-b] [-v] [-G] [-T <threshold_file>]" \
 	    "[-s(how_thresholds)] [-N \| -nocolor] [-C ca_name] [-P ca_port]" \
 	    "[-t(imeout) timeout_ms] <lid|guid> [<port>]"
 	exit -1
 }
 
-function green() {
+green() {
 	if [ "$bw" = "yes" ]; then
 		if [ "$verbose" = "yes" ]; then
 			echo $1
@@ -21,7 +21,7 @@ function green() {
 	fi
 }
 
-function red() {
+red() {
 	if [ "$bw" = "yes" ]; then
 		echo $1
 		return
@@ -29,7 +29,7 @@ function red() {
 	echo -e "\\033[1;031m" $1 "\\033[0;39m"
 }
 
-function show_thresholds() {
+show_thresholds() {
 	echo "SymbolErrorCounter=$SymbolErrorCounter"
 	echo "LinkErrorRecoveryCounter=$LinkErrorRecoveryCounter"
 	echo "LinkDownedCounter=$LinkDownedCounter"
@@ -44,7 +44,7 @@ function show_thresholds() {
 	echo "VL15Dropped=$VL15Dropped"
 }
 
-function get_thresholds() {
+get_thresholds() {
 	. $1
 }
 
@@ -67,6 +67,7 @@ bw=""
 verbose=""
 brief=""
 ca_info=""
+suppress_deprecated="no"
 
 while [ "$1" ]; do
 	case $1 in
@@ -95,6 +96,9 @@ while [ "$1" ]; do
 	-s)
 		show_thresholds
 		exit 0
+		;;
+	-S)
+		suppress_deprecated="yes"
 		;;
 	-P | -C | -t | -timeout)
 		case $2 in
@@ -133,6 +137,10 @@ if [ "$portnum" = "255" ]; then
 	portname="all"
 else
 	portname=$2
+fi
+
+if [ "$suppress_deprecated" = "no" ]; then
+echo "*** WARNING ***: this command is deprecated; Please use \"ibqueryerrors\"\n\n" 1>&2
 fi
 
 if [ "$guid_addr" ]; then
